# Generated by Django 5.1.7 on 2025-03-22 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_crop_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='code',
        ),
        migrations.CreateModel(
            name='CropElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.crop')),
            ],
        ),
    ]
