# Generated by Django 5.1.7 on 2025-03-22 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_crop_code_cropelement'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cropelement',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='code'),
        ),
    ]
