# Generated by Django 5.1.7 on 2025-03-26 13:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_suitabilitylevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeometryFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gridcode', models.IntegerField()),
                ('layer', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
