# Generated by Django 5.1.7 on 2025-03-31 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_geometryfeature"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Crop",
            new_name="LegacyCrop",
        ),
        migrations.RenameModel(
            old_name="CropElement",
            new_name="LegacyCropElement",
        ),
        migrations.RenameModel(
            old_name="GeometryFeature",
            new_name="LegacyGeometryFeature",
        ),
    ]
