# Generated by Django 5.1.7 on 2025-03-31 12:52

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_auto_20250331_1500"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrentCrop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="CurrentCropElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="CurrentGeometryFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gridcode", models.IntegerField()),
                ("layer", models.CharField(max_length=100)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="legacycropelement",
            name="code",
        ),
        migrations.AddConstraint(
            model_name="legacycropelement",
            constraint=models.UniqueConstraint(
                fields=("name", "category"), name="legacy_code"
            ),
        ),
        migrations.AddField(
            model_name="currentcropelement",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.currentcrop"
            ),
        ),
        migrations.AddConstraint(
            model_name="currentcropelement",
            constraint=models.UniqueConstraint(
                fields=("name", "category"), name="current_code"
            ),
        ),
    ]
