# Generated by Django 5.1.7 on 2025-03-31 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_currentcrop_name_alter_currentcropelement_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legacycrop',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
