# Generated by Django 5.1.7 on 2025-03-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_legacycrop_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legacycrop',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
