# Generated by Django 5.1.7 on 2025-03-31 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_legacycrop_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentcrop',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
