# Generated by Django 5.1.7 on 2025-03-31 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_contribution_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentgeometryfeature',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contribution'),
        ),
    ]
