# Generated by Django 5.1.7 on 2025-03-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_currentgeometryfeature_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentcropelement',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='legacycropelement',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
