# Generated by Django 5.1.7 on 2025-03-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_currentcropelement_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legacycropelement',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
