# Generated by Django 5.1.7 on 2025-04-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_contribution_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentgeometryfeature',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
