# Generated by Django 5.1.7 on 2025-04-06 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_currentgeometryfeature_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentgeometryfeature',
            name='reference',
        ),
        migrations.AddField(
            model_name='contribution',
            name='geom2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.currentgeometryfeature'),
        ),
    ]
