# Generated by Django 5.1.7 on 2025-04-06 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_currentgeometryfeature_reference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='geom',
        ),
    ]
