# Generated by Django 5.1.7 on 2025-04-06 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_contribution_geom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribution',
            old_name='geom2',
            new_name='geom',
        ),
    ]
