# Generated by Django 5.1.7 on 2025-04-18 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_contribution_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='geom',
        ),
        migrations.AddField(
            model_name='currentgeometryfeature',
            name='reference',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.contribution'),
            preserve_default=False,
        ),
    ]
