# Generated by Django 5.1.7 on 2025-04-19 08:37

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_contribution_geom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentgeometryfeature',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
    ]
