# Generated by Django 5.1.7 on 2025-04-20 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_currentgeometryfeature_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentgeometryfeature',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geometries', to='api.contribution'),
        ),
    ]
