# Generated by Django 5.1.7 on 2025-04-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_currentgeometryfeature_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentgeometryfeature',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
